spring.application.name=companystrator

#DB config
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#Jwt params
application.security.jwt.private-key-path=keys/private_key.pem
application.security.jwt.public-key-path=keys/public_key.pem

#Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.group-configs[0].group=default
springdoc.api-docs.group-configs[0].packages-to-scan=com.companystrator
springdoc.api-docs.group-configs[0].packages-to-exclude=com.companystrator.exceptions.controller